// Generated by Wrangler on Wed Jul 24 2024 23:24:32 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	CANVAS_SNAPS: KVNamespace;
	RECOMMENDATIONS: KVNamespace;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	NEXTAUTH_SECRET: string;
	DATABASE_URL: string;
	NEXTAUTH_URL: string;
	BACKEND_SECURITY_KEY: string;
	BACKEND_BASE_URL: string;
	STORAGE: R2Bucket;
	DATABASE: D1Database;
	AI: Ai;
}
