name = "supermemory"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"


kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "f663564d9a4e4ebc904a5fb4301ab6a6" },
	{ binding = "RECOMMENDATIONS", id = "bf3f293fb589406e961dfd91e43c48bd" }
]

env.production.kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "f663564d9a4e4ebc904a5fb4301ab6a6" },
	{ binding = "RECOMMENDATIONS", id = "bf3f293fb589406e961dfd91e43c48bd" }
]

[ai]
binding = "AI"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "supermemory-r2-preview"

[[d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "5e11c666-eece-4ef5-8d35-5b20636f7ce7"


[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-prod"
database_id = "2531ff71-861b-4815-bde8-aa0a36b9ed09"

[env.preview.ai]
binding = "AI"

[[env.preview.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "5e11c666-eece-4ef5-8d35-5b20636f7ce7"

[env.production.ai]
binding = "AI"